### ISSUE TITLE
Walter é malandro! HAHAHA

### ISSUE THREAD

**Issue by nelsonmatenda** [EdAnder32/Master-Key#6]
Fiquei a ver o pull request que aceitaste dele! ele apagou o teu nome Edmilson, em todo lugar que ele encontrou hahahahahahahaha

**Comment by EdAnder32** [comment]
Tenho que deixar dessa vida de aceitar requests sem verificar tudo
Vou rever a cena

**Comment by nelsonmatenda** [comment]
Verifica mesmo
